steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ethereal-shine-337102/github.com/eranga88/cloud-build:$SHORT_SHA', '.'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ethereal-shine-337102/github.com/eranga88/cloud-build:$SHORT_SHA']
