steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/just-me-production-334913/github.com/eranga88/cloud-build:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/just-me-production-334913/github.com/eranga88/cloud-build:$SHORT_SHA']
